# Generated by Django 3.1.3 on 2020-11-15 20:13

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0004_auto_20201115_1813'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_bestseller',
            field=models.BooleanField(db_index=True, default=False, verbose_name='популярные товары'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='описание'),
        ),
    ]
