# Generated by Django 3.1.3 on 2020-11-15 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0005_auto_20201115_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_news',
            field=models.BooleanField(db_index=True, default=False, verbose_name='новый товар'),
        ),
    ]
