# Generated by Django 3.1.3 on 2020-11-15 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0006_product_is_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_news',
            new_name='is_new',
        ),
    ]
