# Generated by Django 3.1.3 on 2020-11-16 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0007_auto_20201116_0129'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.SlugField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'направления',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('slug', models.SlugField(null=True, unique=True)),
                ('business_direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='spaweb.businessdirection')),
            ],
            options={
                'verbose_name_plural': 'группы категорий',
            },
        ),
        migrations.AddField(
            model_name='productcategory',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_categories', to='spaweb.topic'),
        ),
    ]
