# Generated by Django 3.1.2 on 2020-11-16 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0008_businessdirection_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': 'группы категорий'},
        ),
        migrations.AddField(
            model_name='productcategory',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products_categories', to='spaweb.topic'),
        ),
        migrations.AddField(
            model_name='topic',
            name='business_direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='spaweb.businessdirection'),
        ),
    ]
