# Generated by Django 3.1.3 on 2020-11-22 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0010_auto_20201120_2321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='user',
        ),
    ]
