# Generated by Django 3.1.3 on 2020-11-30 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0011_remove_customer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.TextField(null=True, verbose_name='адрес для доставки'),
        ),
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='address', to='spaweb.city', verbose_name='город доставки'),
        ),
        migrations.AddField(
            model_name='customer',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer', to='spaweb.order'),
        ),
        migrations.DeleteModel(
            name='ShippingAddress',
        ),
    ]
