# Generated by Django 3.1.2 on 2020-12-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0013_orderitem_order_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.RemoveField(
            model_name='product',
            name='city',
        ),
        migrations.AddField(
            model_name='product',
            name='city',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_products', to='spaweb.city', verbose_name='город'),
        ),
    ]
