# Generated by Django 3.1.2 on 2020-12-03 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0014_auto_20201203_1359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='order_cost',
        ),
    ]
