# Generated by Django 3.1.3 on 2021-01-17 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0016_auto_20201208_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sber_id',
            field=models.TextField(blank=True, null=True, verbose_name='ID заказа в сбербанке'),
        ),
    ]
