# Generated by Django 3.1.3 on 2021-01-23 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0017_order_sber_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_method',
        ),
    ]
