# Generated by Django 3.1.3 on 2022-12-03 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaweb', '0018_remove_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='promocode',
            field=models.TextField(blank=True, null=True, verbose_name='Промокод'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='фото товара'),
        ),
    ]
